name: chezmoi

on:
  push:
    branches: [main]
    paths: [chezmoi/**]
  workflow_dispatch:

jobs:
  update:
    strategy:
      matrix:
        node: [wolfe-pi5]
    runs-on: ${{ matrix.node }}
    concurrency:
      group: ${{ matrix.node }}
      cancel-in-progress: false
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: chezmoi update --init --no-tty

      - if: failure()
        run: |
          scripts/alert.sh "chezmoi update failed on ${{ matrix.node }}" \
            "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_number }}"
