name: garage layout

on:
  workflow_dispatch:

concurrency:
  group: MacMini
  cancel-in-progress: false

jobs:
  init:
    runs-on: MacMini
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v7
      - working-directory: garage/layout
        run: lab init --auto-approve
