name: gatus health

on:
  schedule:
    - cron: "11-59/15 * * * *"
  workflow_dispatch:

jobs:
  health:
    runs-on: MacMini
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - working-directory: gatus
        run: dotnet run --project ../build/src/Wolfe.Lab.Build -- health
