name: gatus

services:
  gatus:
    image: ghcr.io/twin/gatus:v5.36.0
    container_name: gatus
    restart: unless-stopped
    environment:
      TZ: Europe/London
      GATUS_CONFIG_PATH: /config
      LAB_HOST: macmini.tailf823b8.ts.net
    env_file:
      - ${HOME}/Docker/gatus/gatus.env
    volumes:
      - ./config:/config:ro
      - ${HOME}/Docker/gatus/data:/data
    ports:
      - "8280:8080"
