# Utilities
cask "1password"
cask "airbuddy"
cask "daisydisk"
cask "google-chrome"
cask "google-drive"
cask "nordvpn"
cask "paste"
cask "shottr"
cask "vorssaint"

# Drivers
cask "displaylink"

# Productivity
cask "claude"
cask "chatgpt"
cask "obsidian"

# Social
cask "discord"

# Media
cask "affinity"
cask "spotify"

# Developer Tools
cask "claude-code"
brew "cloc"
cask "docker-desktop"
brew "gh"
brew "git"
cask "jetbrains-toolbox"
brew "mkcert"
brew "opentofu"
brew "ollama"
brew "sqlite"
cask "visual-studio-code"