apiVersion: 1

contactPoints:
  - orgId: 1
    name: pushover
    receivers:
      - uid: pushover
        type: pushover
        settings:
          apiToken: $PUSHOVER_APP_TOKEN
          userKey: $PUSHOVER_USER_KEY

  - orgId: 1
    name: watchdog
    receivers:
      - uid: watchdog
        type: webhook
        settings:
          url: https://hc-ping.com/$HEALTHCHECKS_PING_KEY/lab-grafana-watchdog
          httpMethod: POST
