<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="Wolfe.Lab.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ritten.Core" />
    <PackageReference Include="Vogen" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Ritten.Engine" />
    <Using Include="Vogen" />
  </ItemGroup>

</Project>
