using Wolfe.Lab.Domain.Catalog.Components.Models;
using Wolfe.Lab.Infrastructure.Ollama;

namespace Wolfe.Lab.Tests.Application.Workflows.Ollama;

public class OllamaModelfileTests
{
    // As `ollama show --modelfile` prints a model made from another: its comments, the weights it
    // shares, a template whose body is passed over, and its parameters.
    private const string Shown = """"
        # Modelfile generated by "ollama show"
        # To build a new Modelfile based on this, replace FROM with:
        # FROM lab/interactive:latest

        FROM /Users/lab/.ollama/models/blobs/sha256-78b3
        TEMPLATE """{{ .Prompt }}
        FROM inside the template is not a FROM
        """
        PARAMETER temperature 0.7
        PARAMETER num_ctx 16384
        """";

    [Fact]
    public void Parse_TakesTheWeightsAndParameters()
    {
        var modelfile = OllamaModelfile.Parse(Shown);

        modelfile.Weights.ShouldBe(["/Users/lab/.ollama/models/blobs/sha256-78b3"]);
        modelfile.Parameters.ShouldBe(new Dictionary<string, string> { ["temperature"] = "0.7", ["num_ctx"] = "16384" });
        modelfile.Context.ShouldBe(ContextLength.From(16384));
    }

    [Fact]
    public void Context_IsNoneWhenTheModelSetsNone() =>
        OllamaModelfile.Parse("FROM /blobs/sha256-1\n").Context.ShouldBeNull();
}
